DROP DATABASE IF EXISTS userdb;
DROP USER IF EXISTS `project_user`@`%`;
CREATE DATABASE IF NOT EXISTS userdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `project_user`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `userdb`.* TO `project_user`@`%`;
FLUSH PRIVILEGES;
DROP DATABASE IF EXISTS appointmentdb;
DROP USER IF EXISTS `userdb`@`%`;
CREATE DATABASE IF NOT EXISTS appointmentdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `project_user`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `appointmentdb`.* TO `project_user`@`%`;
FLUSH PRIVILEGES;